In [1]:
import numpy as np

a = np.array([2,3,4])

print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# preforming basic opretions
# Addition
import numpy as np

array1 = np.array([2,2,6,8])
array2 = np.array([1,2,3,4])

# Addition
result1 = array1 + array2
print(result1)

#Subtraction
result2 = array1 - array2
print(result2)

#multiplication
result3 = array1 * array2
print(result3)

#Division
result4 = array1 / array2
print(result4)

#square root
result5 = np.sqrt(array1)
print("sqr",result5)

#summation
result6 = np.sum(array1)
print("sum",result6)

#Mean
result7 = np.mean(array1)
print("mean",result7)

#maximum and minimum
result8 = np.max(array2)
result9 = np.min(array2)
print(result8 ,"   ",result9)


[ 3  4  9 12]
[1 0 3 4]
[ 2  4 18 32]
[2. 1. 2. 2.]
sqr [1.41421356 1.41421356 2.44948974 2.82842712]
sum 18
mean 4.5
4     1


In [18]:
#2D and 3D array
import numpy as np
print("---------2D Array------------")
array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D)
print(array_2D.size)
print(array_2D.shape)   # row 2 colomn 4

print("---------3D Array------------")
array_3D = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(array_3D)
print(array_3D.size)
print(array_3D.shape)   # outerMost 2  rowof2D array2 column4

print(array_2D.dtype)

---------2D Array------------
[[1 2 3 4]
 [5 6 7 8]]
8
(2, 4)
---------3D Array------------
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
16
(2, 2, 4)
int64


In [20]:
# check Array details
import numpy as np

array_1 = np.array([5,6,7,8])
array_2 = np.array([[1,2,3,4],[5,6,7,8]])
array_3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

print(array_1.ndim)
print(array_2.ndim)
print(array_3.ndim)

1
2
3


In [24]:
#Array indexing

array_1 = np.array([5,6,7,8])
array_2 = np.array([[1,2,3,4],[5,6,7,8]])
array_3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

print(array_1[3])
print(array_2[0,2])
print(array_3[0,1,2])



8
3
7


In [27]:
# 1.create a 2d numpy arrray which has daimentions 4 ^ 5 which contains the numbers 1 to 20
# performe the following only arry
# * add 10 to evry element
# * multiply every elemet by 2
# * calculate square of each element
import numpy as np

array_1= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

result_1 = array_1 + 10
print(result_1)

result_2 = array_1*2
print(result_2)

result_3 = array_1**2
print(result_3)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


In [35]:
#filter elements
import numpy as np
arr =  np.array([10,20,30,40,50,60,70])

#step by steps
condition = arr > 25
print(condition)

filterdArr = arr[condition]
print(filterdArr)

#------------------------
#one step
filterdArr1 = arr[arr >25]
print(filterdArr1)


#multiple conditions
filterdArr2 = arr[(arr > 20)&(arr < 50)]
print(filterdArr2)


[False False  True  True  True  True  True]
[30 40 50 60 70]
[30 40 50 60 70]
[30 40]


In [2]:
#initialization Array
import numpy as np

#-------------------------------------------zeros function------------------
array1 = np.zeros(5 ,dtype="int")
print(array1)

array2 = np.zeros((2,3))
print(array2)

#-------------------------------------------full function------------------

array3 = np.full(4, 7)
print(array3)

array4 = np.full((2,3), 10)
print(array4)

array5 = np.full((2,3), [1,2,3])
# print(array5)


#-------------------------------------------emty function------------------
#value widihata garbage values assing wenawa mekedi
array6 = np.empty((2,3), dtype="int")
print(array6)


[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[7 7 7 7]
[[10 10 10]
 [10 10 10]]
[[1 2 3]
 [1 2 3]]


In [82]:
#Q1
import numpy as np
arra_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
evenArr = arra_1[arra_1%2==0]
print(evenArr)


#Q2
arra_2 = np.array([10,20,30,40,50])
resultArr = arra_2[arra_2 > np.mean(arra_2) ]
print(resultArr)

[ 2  4  6  8 10 12 14 16 18 20]
[40 50]
